# Generated by Django 3.1.7 on 2021-11-08 13:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dateCreated',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 13, 30, 5, 317289, tzinfo=utc)),
        ),
    ]
